### ISSUE TITLE
[BUG]: Goroutine leak in processItems since v2.0

### ISSUE THREAD

**Issue by aeneasr** [dgraph-io/ristretto#422]
### What version of Ristretto are you using?

Upgrading from 1.0->2.0

### What version of Go are you using?

1.23

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

macOS m4

### What steps will reproduce the bug?

Run tests in `ory/x` with goleak detection: https://github.com/ory/x/actions/runs/12176814014/job/33963319842?pr=829#step:12:501

### Expected behavior and actual result.

This leak happens only after upgrading to ristretto v2

### Additional information

```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 13 in state select, with github.com/dgraph-io/ristretto/v2.(*defaultPolicy[...]).processItems on top of the stack:
goroutine 13 [select]:
github.com/dgraph-io/ristretto/v2.(*defaultPolicy[...]).processItems(0x12bdb10)
	/home/runner/go/pkg/mod/github.com/dgraph-io/ristretto/v2@v2.0.0/policy.go:70 +0x7f
created by github.com/dgraph-io/ristretto/v2.newDefaultPolicy[...] in goroutine 12
	/home/runner/go/pkg/mod/github.com/dgraph-io/ristretto/v2@v2.0.0/policy.go:54 +0x165

 Goroutine 14 in state select, with github.com/dgraph-io/ristretto/v2.(*Cache[...]).processItems on top of the stack:
goroutine 14 [select]:
github.com/dgraph-io/ristretto/v2.(*Cache[...]).processItems(0x13c9440)
	/home/runner/go/pkg/mod/github.com/dgraph-io/ristretto/v2@v2.0.0/cache.go:518 +0x165
created by github.com/dgraph-io/ristretto/v2.NewCache[...] in goroutine 12
	/home/runner/go/pkg/mod/github.com/dgraph-io/ristretto/v2@v2.0.0/cache.go:261 +0x5a9
]
```

**Comment by aeneasr** [comment]
I could imagine the problem being holding to the pointer of defaultPolicy: https://github.com/dgraph-io/ristretto/compare/v1.0.0...v2.0.0#diff-b2eb74c816d6381ef0c5306d99c2ba6de8fc5538f5dc57535d7fd7dc36153042R56

But really, I have no clue about the inner workings of ristretto

**Comment by mangalaman93** [comment]
Thank you for filing the issue @aeneasr. Let me look into it.

**Comment by aeneasr** [comment]
Amazing, thank you!

**Comment by mangalaman93** [comment]
Released v2.0.1 as well in case you would like to upgrade. I think this should fix the issue, but let us know if you see this again. Happy to look into it.

**Comment by aeneasr** [comment]
Thanks! Unfortunately, the issue persists after upgrading to 2.1.0:

https://github.com/ory/x/actions/runs/12953319112/job/36132708986#step:12:499

**Comment by mangalaman93** [comment]
1. Are you closing the cache after using it?
2. It is possible that goroutine survives a few moments after `Close` returns because it still has to execute `return` statement. Is that what may be causing the tests to fail?
3. Could you point me to the code for the test?
